version: '3.1'
services:
  db:
    image: "mysql"
    container_name: mysql_mine_mera
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: grafana/grafana
    ports:
      - 3090:3000